"""
CsvVerifier.py
Robot Framework custom library for verifying downloaded CSV report files.
Used by the Reports module test suite (t6.1).

Actual CSV structure produced by the Reports module:
  Row 1  : "Generated by, <user>"
  Row 2  : "Opening balance for <date range>", "PHP <amount>"
  Row 3  : "Closing balance for <date range>", "PHP <amount>"
  Row 4  : Empty
  Row 5  : Column headers (Transaction ID, Transaction Type, ...)
  Row 6+ : Data rows

Rows are located dynamically so the parser is resilient to future
preamble additions.

Actual Transaction Type values in production:
  "Internal Transfer"  — internal fund transfers (excluded from balance)
  "External Transfer"  — external fund transfers (included in balance)
  "Cash Deposit"       — cash deposits           (increases balance)
  "Cash Withdrawal"    — cash withdrawals        (decreases balance)
  "Interest Crediting" — interest credits        (excluded from balance)

Balance formula:
  Closing Balance = Opening Balance
                  + sum(Transaction Amount for Cash Deposit rows)
                  + sum(Transaction Amount for Cash Withdrawal rows)

  Cash Withdrawal amounts are already negative in the CSV.
  External Transfer, Internal Transfer, and Interest Crediting are excluded.
"""

import csv
import re
from datetime import datetime


class CsvVerifier:
    ROBOT_LIBRARY_VERSION = "1.0.0"

    EXPECTED_HEADERS = [
        "Transaction ID",
        "Transaction Type",
        "Date & Time",
        "Debit Account Name",
        "Debit Account Number",
        "Credit Account Name",
        "Credit Account Number",
        "Transaction Amount",
        "Service Fee Amount",
        "Total Amount",
        "Status",
    ]

    # Types whose Transaction Amount contributes to the closing balance.
    # Only Cash Deposit and Cash Withdrawal affect the teller EOD balance.
    # External Transfer, Internal Transfer, and Interest Crediting are excluded.
    BALANCE_INCLUDED_TYPES = {"Cash Deposit", "Cash Withdrawal"}

    # ------------------------------------------------------------------ #
    #  Internal parser — locates rows dynamically                         #
    # ------------------------------------------------------------------ #

    def _parse_csv(self, filepath):
        """
        Parses the CSV file by locating key rows dynamically.
        Returns: (closing_row, opening_row, headers_list, data_rows_list_of_dicts)

        closing_row  : row containing "Closing balance"
        opening_row  : row containing "Opening balance" (None if absent)
        headers_list : column header row (starts with "Transaction ID")
        data_rows    : list of dicts keyed by header
        """
        with open(filepath, newline="", encoding="utf-8-sig") as f:
            all_rows = list(csv.reader(f))

        opening_row = None
        closing_row = None
        header_idx  = None

        for i, row in enumerate(all_rows):
            if not row:
                continue
            first = row[0].strip()
            if "opening balance" in first.lower():
                opening_row = row
            elif "closing balance" in first.lower():
                closing_row = row
            elif first == "Transaction ID":
                header_idx = i
                break

        if closing_row is None:
            raise AssertionError(
                f'CSV "{filepath}": could not find a "Closing balance" row.'
            )
        if header_idx is None:
            raise AssertionError(
                f'CSV "{filepath}": could not find header row starting with "Transaction ID".'
            )

        headers   = all_rows[header_idx]
        data_rows = [
            dict(zip(headers, row))
            for row in all_rows[header_idx + 1:]
            if any(cell.strip() for cell in row)
        ]

        return closing_row, opening_row, headers, data_rows

    @staticmethod
    def _parse_amount(raw):
        """Strips currency prefixes (PHP, ₱), commas, and whitespace then returns a float."""
        cleaned = raw.replace("PHP", "").replace("₱", "").replace(",", "").strip()
        return float(cleaned)

    # ------------------------------------------------------------------ #
    #  File name                                                           #
    # ------------------------------------------------------------------ #

    def verify_csv_file_name(self, filename, report_date):
        """
        Asserts the file name matches:
          <bank-name>_transactions_report_<DD_Mon_YYYY>[_to_<DD_Mon_YYYY>].csv

        - report_date : start/closing date in YYYY-MM-DD format;
                        converted to DD_Mon_YYYY before checking presence.
        """
        if "_transactions_report_" not in filename:
            raise AssertionError(
                f'File name "{filename}" does not contain "_transactions_report_".\n'
                f"Expected: <bank-name>_transactions_report_<date(s)>.csv"
            )
        if not filename.endswith(".csv"):
            raise AssertionError(
                f'File name "{filename}" does not have a .csv extension.'
            )
        if report_date:
            formatted = datetime.strptime(report_date, "%Y-%m-%d").strftime("%d_%b_%Y")
            if formatted not in filename:
                raise AssertionError(
                    f'File name "{filename}" does not contain "{formatted}" '
                    f'(converted from "{report_date}").'
                )

    # ------------------------------------------------------------------ #
    #  Summary row                                                         #
    # ------------------------------------------------------------------ #

    def verify_csv_summary_row(self, filepath):
        """
        Asserts the CSV contains a Closing balance row.
        Returns the raw closing balance string (e.g. "PHP 120,891,727.90") for logging.
        """
        closing_row, _, _, _ = self._parse_csv(filepath)

        balance = closing_row[1].strip() if len(closing_row) > 1 else ""
        if not balance:
            raise AssertionError("Closing balance row has no value in column 2.")

        return balance

    # ------------------------------------------------------------------ #
    #  Headers                                                             #
    # ------------------------------------------------------------------ #

    def verify_csv_headers(self, filepath):
        """
        Asserts the CSV has exactly the 10 expected column headers in order.
        """
        _, _, actual_headers, _ = self._parse_csv(filepath)

        if actual_headers != self.EXPECTED_HEADERS:
            raise AssertionError(
                f"CSV headers mismatch.\n"
                f"Expected : {self.EXPECTED_HEADERS}\n"
                f"Actual   : {actual_headers}"
            )

    # ------------------------------------------------------------------ #
    #  Row count                                                           #
    # ------------------------------------------------------------------ #

    def verify_csv_has_rows(self, filepath):
        """
        Asserts the CSV has at least one data row.
        Returns the row count for logging.
        """
        _, _, _, data_rows = self._parse_csv(filepath)

        if not data_rows:
            raise AssertionError(
                f'CSV "{filepath}" contains no data rows.'
            )
        return len(data_rows)

    # ------------------------------------------------------------------ #
    #  Date & Time format and range                                        #
    # ------------------------------------------------------------------ #

    _DT_PATTERN = re.compile(r"^\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}$")

    def verify_csv_date_format_and_range(self, filepath, date_from, date_to):
        """
        Asserts every "Date & Time" cell:
          1. Matches format  yyyy/mm/dd hh:mm:ss
          2. Falls within the given date range (inclusive)

        date_from / date_to must be in YYYY-MM-DD format.
        """
        df = date_from.replace("-", "/")    # "2026/03/10"
        dt = date_to.replace("-", "/")

        _, _, _, data_rows = self._parse_csv(filepath)
        errors = []

        for i, row in enumerate(data_rows, start=6):   # data starts at row 6 with new format
            cell = row.get("Date & Time", "")

            if not self._DT_PATTERN.match(cell):
                errors.append(
                    f'Row {i}: "{cell}" — does not match yyyy/mm/dd hh:mm:ss'
                )
                continue

            date_part = cell[:10]
            if not (df <= date_part <= dt):
                errors.append(
                    f'Row {i}: "{date_part}" — outside range [{df} to {dt}]'
                )

        if errors:
            raise AssertionError(
                f"Date & Time errors in '{filepath}':\n" + "\n".join(errors)
            )

    # ------------------------------------------------------------------ #
    #  Internal transaction presence                                       #
    # ------------------------------------------------------------------ #

    def verify_csv_internal_transactions_present(self, filepath):
        """
        Warns (does not fail) if no "Internal Transfer" transactions appear in the CSV.
        Internal transactions must be present in the report even though they
        are excluded from the closing balance.
        """
        _, _, _, data_rows = self._parse_csv(filepath)
        found = any(
            row.get("Transaction Type", "").strip() == "Internal Transfer"
            for row in data_rows
        )
        if not found:
            print(
                "[CsvVerifier] NOTE: No 'Internal' transactions found in this period — "
                "acceptable if none occurred in the selected date range."
            )
        return found

    # ------------------------------------------------------------------ #
    #  Balance verification                                                #
    # ------------------------------------------------------------------ #

    def verify_csv_balance_matches_summary(self, filepath):
        """
        Computes the closing balance from the data rows and asserts it matches
        the value stated in the summary row (row 1).

        Balance formula:
          Sum of Transaction Amounts for rows where Transaction Type is
          "Deposit", "Withdraw", or "External" (Success only).
          Transaction Amounts are already signed in the CSV, so a plain
          sum of included rows gives the correct result.

          "Internal" rows are always excluded.
          "External" rows for Failed transactions are also excluded per spec,
          but cannot be identified without a Status column — if the computed
          balance does not match the summary, check for Failed External
          transactions in the selected date range.
        """
        closing_row, opening_row, _, data_rows = self._parse_csv(filepath)

        # --- Parse closing balance ---
        raw_closing = closing_row[1].strip() if len(closing_row) > 1 else ""
        try:
            closing_balance = self._parse_amount(raw_closing)
        except (ValueError, IndexError):
            raise AssertionError(
                f'Cannot parse closing balance from "{raw_closing}".'
            )

        # --- Parse opening balance ---
        opening_balance = 0.0
        if opening_row and len(opening_row) > 1:
            try:
                opening_balance = self._parse_amount(opening_row[1].strip())
            except ValueError:
                opening_balance = 0.0

        # --- Sum included transaction amounts ---
        txn_sum = 0.0
        skipped = []

        for i, row in enumerate(data_rows, start=6):
            txn_type = row.get("Transaction Type", "").strip()
            if txn_type not in self.BALANCE_INCLUDED_TYPES:
                continue

            raw_amount = row.get("Transaction Amount", "").strip()
            try:
                txn_sum += self._parse_amount(raw_amount)
            except ValueError:
                skipped.append(f'Row {i}: could not parse amount "{raw_amount}"')

        computed = round(opening_balance + txn_sum, 2)

        if skipped:
            print("[CsvVerifier] Skipped rows during balance computation:\n"
                  + "\n".join(skipped))

        # --- Compare ---
        if computed != closing_balance:
            raise AssertionError(
                f"Closing balance mismatch.\n"
                f"  Opening balance : {opening_balance}\n"
                f"  Transaction sum : {round(txn_sum, 2)}\n"
                f"  Computed        : {computed}\n"
                f"  CSV closing     : {closing_balance}\n"
                f"  Diff            : {round(computed - closing_balance, 2)}\n"
                f"  Included types  : {sorted(self.BALANCE_INCLUDED_TYPES)}\n"
                f"  NOTE: Only Cash Deposit and Cash Withdrawal are included in the\n"
                f"  balance computation. If the diff is unexpected, check for\n"
                f"  transaction types that may have been added to the report."
            )

        return computed
